### ISSUE TITLE
It is not supporting php 8.1

### ISSUE THREAD

**Issue by harsh4you07** [sizeg/yii2-jwt#41]
we are getting below error, 

 lcobucci/jwt[3.3.0, ..., 3.3.x-dev] require php ^5.6 || ^7.0 -> your php version (8.1.7) does not satisfy that requirement.
    - sizeg/yii2-jwt[v2.0.0, ..., v2.0.2] require lcobucci/jwt ~3.3.0 -> satisfiable by lcobucci/jwt[3.3.0, ..., 3.3.x-dev].
    - Root composer.json requires sizeg/yii2-jwt ^2.0 -> satisfiable by sizeg/yii2-jwt[v2.0.0, v2.0.1, v2.0.1.1, v2.0.2].

**Comment by AbdullahAlfar** [comment]
It is not supporting php 8.1  please

**Comment by sizeg** [comment]
Thank you for the report. i'll try to fix it this week

**Comment by numelion** [comment]
> Thank you for the report. i'll try to fix it this week

Still waiting for version 8.1 support...

**Comment by cozumel424** [comment]
https://github.com/lcobucci/jwt/issues/843#issuecomment-1124514766

All you need to do is update your composer json. Thanks for your work, it's a good package.

**Comment by numelion** [comment]
@sizeg hello, when will you upgrade the composer json to `lcobucci/jwt:^4`? I really need your package

**Comment by floor12** [comment]
Yes, php 8.x support is needed...

**Comment by cxpreng** [comment]
Sadly it's not supporting php8.x because it's using an outdated version of lcobucci/jwt, All packages from that repo below 4.2.0 have security issues, and given this is a security tool, without an update and if it's not gonna be keeped up to date it's not even worth trying it, move to some other package or try a node.js implementation

**Comment by sizeg** [comment]
https://github.com/sizeg/yii2-jwt/tree/v4.0-beta
